export default [
    { abbreviation: "AK", stateName: "Alaska" },
    { abbreviation: "AL", stateName: "Alabama" },
    { abbreviation: "AR", stateName: "Arkansas" },
    { abbreviation: "AS", stateName: "American Samoa" },
    { abbreviation: "AZ", stateName: "Arizona" },
    { abbreviation: "CA", stateName: "California" },
    { abbreviation: "CO", stateName: "Colorado" },
    { abbreviation: "CT", stateName: "Connecticut" },
    { abbreviation: "DC", stateName: "District of Columbia" },
    { abbreviation: "DE", stateName: "Delaware" },
    { abbreviation: "FL", stateName: "Florida" },
    { abbreviation: "GA", stateName: "Georgia" },
    { abbreviation: "GU", stateName: "Guam" },
    { abbreviation: "HI", stateName: "Hawaii" },
    { abbreviation: "IA", stateName: "Iowa" },
    { abbreviation: "ID", stateName: "Idaho" },
    { abbreviation: "IL", stateName: "Illinois" },
    { abbreviation: "IN", stateName: "Indiana" },
    { abbreviation: "KS", stateName: "Kansas" },
    { abbreviation: "KY", stateName: "Kentucky" },
    { abbreviation: "LA", stateName: "Louisiana" },
    { abbreviation: "MA", stateName: "Massachusetts" },
    { abbreviation: "MD", stateName: "Maryland" },
    { abbreviation: "ME", stateName: "Maine" },
    { abbreviation: "MI", stateName: "Michigan" },
    { abbreviation: "MN", stateName: "Minnesota" },
    { abbreviation: "MO", stateName: "Missouri" },
    { abbreviation: "MS", stateName: "Mississippi" },
    { abbreviation: "MT", stateName: "Montana" },
    { abbreviation: "NC", stateName: "North Carolina" },
    { abbreviation: "ND", stateName: "North Dakota" },
    { abbreviation: "NE", stateName: "Nebraska" },
    { abbreviation: "NH", stateName: "New Hampshire" },
    { abbreviation: "NJ", stateName: "New Jersey" },
    { abbreviation: "NM", stateName: "New Mexico" },
    { abbreviation: "NV", stateName: "Nevada" },
    { abbreviation: "NY", stateName: "New York" },
    { abbreviation: "OH", stateName: "Ohio" },
    { abbreviation: "OK", stateName: "Oklahoma" },
    { abbreviation: "OR", stateName: "Oregon" },
    { abbreviation: "PA", stateName: "Pennsylvania" },
    { abbreviation: "PR", stateName: "Puerto Rico" },
    { abbreviation: "RI", stateName: "Rhode Island" },
    { abbreviation: "SC", stateName: "South Carolina" },
    { abbreviation: "SD", stateName: "South Dakota" },
    { abbreviation: "TN", stateName: "Tennessee" },
    { abbreviation: "TX", stateName: "Texas" },
    { abbreviation: "UT", stateName: "Utah" },
    { abbreviation: "VA", stateName: "Virginia" },
    { abbreviation: "VI", stateName: "Virgin Islands" },
    { abbreviation: "VT", stateName: "Vermont" },
    { abbreviation: "WA", stateName: "Washington" },
    { abbreviation: "WI", stateName: "Wisconsin" },
    { abbreviation: "WV", stateName: "West Virginia" },
    { abbreviation: "WY", stateName: "Wyoming" }
];